import pandas as pd

splits = {'test': 'data/test-00000-of-00001.parquet', 'testmini': 'data/testmini-00000-of-00001.parquet'}
df_testmini = pd.read_parquet("hf://datasets/shivank21/algebra/" + splits["testmini"])

solution=["Each train has 31 wagons and moves in opposite directions. When wagon 7 of the first train aligns with wagon 12 of the second, the numbering shifts inversely. The relation is: 7 <-> 12. Moving from wagon 7 to wagon 11 in the first train means shifting 4 positions forward. Since the second train moves oppositely, its corresponding number decreases by 4: 12−4=8. So, wagon 11 of the first train aligns with wagon 8 of the second.",
           "Here’s the reasoning in a clear sequence: Start with 4 apples and 5 bananas.Convert 3 apples → 1 banana → New count: 1 apple, 6 bananas. Convert 3 bananas → 1 apple → New count: 2 apples, 3 bananas.Convert 3 bananas → 1 apple → New count: 3 apples, 0 bananas.Convert 3 apples → 1 banana → Final count: 0 apples, 1 banana.Thus, the final answer is (A) 1 banana.",
           "The numbers around each house must sum to 20.For the left house, we know 6 (top), 2 (left), and 5 (bottom). Let X be the missing number on the middle right. Equation: 6 + 2 + 5 + X + Middle = 20.Simplifies to 13 + X + Middle = 20 → X + Middle = 7. For the right house, we know 3 (top) and 1 (bottom), with Y missing on the right.Equation: 3 + Y + 1 + Middle + X = 20. Substituting X + Middle = 7, we get 3 + Y + 1 + 7 = 20. Simplifies to 4 + Y + 7 = 20 → Y = 9. Thus, the missing number (?) is 9.",
           "The equation given is:10 + ? + ? + 2 = 18. Step-by-step solution:    Combine known values:    10 + 2 = 12, so the equation simplifies to:    12 + ? + ? = 18. Represent unknown values:    Let X be the missing number:    12 + X + X = 18.    Solve for X:    2X = 18 - 12    2X = 6    X = 3. Thus, the missing number ? is 3",
           "154 cannot appear in the shaded cell because it must be the product of two numbers from the second row, which themselves are products of numbers from the first row. The prime factorization of 154 is **2 × 7 × 11**, meaning it requires at least three distinct prime factors. However, the triangle follows a multiplication rule where each level is derived from exactly two factors above it, making it impossible to form 154 from only two preceding numbers under these constraints.",
           "To determine the number of disjoint regions inside the final 16-sided polygon, let's analyze the pattern step by step:    Starting Shape: We begin with an equilateral triangle (n=3), which has 1 region.    Adding the First Circle: The circumcircle of the triangle does not increase the number of regions.    Adding a Square (n=4): The square intersects the circle, dividing the interior into additional regions.    Adding a Pentagon (n=5): The pentagon introduces more intersections, increasing the count.    Continuing the Process: Each new polygon increases the number of intersections and internal divisions.    General Formula: The total number of regions formed inside a regular nn-sided polygon with this stepwise construction follows a known pattern, leading to:    R(16)=248    Final Answer: After constructing up to the 16-sided polygon, the total number of disjoint regions inside it is 248.",
           "Multiplying a four-digit number by a three-digit number gives a five-digit product 56***, with partial sums 22**, 90*, and **2; summing the digits of 56***, knowing 5 and 6 are fixed, the remaining digits must total 5 to satisfy 5 + 6 + * + * + * = 16, confirming the answer is 16.",
           "Each octagon has 8 sides, so 61 octagons contribute 61×8=488 rods if separate. However, shared edges reduce the count. Each square connects four octagons, contributing 4 new rods while reducing redundancies. The correct formula for this pattern is R=6n+2, where n is the number of octagons. Substituting n=61, we get R=6(61)+2=366+80=446. Thus, the total number of rods in the structure is 446.",
           "To determine x, we note that each pair of connected vertices must sum to the same total. Given the numbers 1 and 4, we establish the uniform sum required across all hexagon edges. By balancing the sums symmetrically and solving for x, we find that x=1 ensures all conditions hold.",
           "Let the five numbers be \( a, b, c, d, e \) with \( a = 2 \) and \( e = 12 \). Given \( a \cdot b \cdot c = 30 \), \( b \cdot c \cdot d = 90 \), and \( c \cdot d \cdot e = 360 \), dividing the second by the first gives \( d = 3b \), and dividing the third by the second gives \( e = 4b \), solving \( 12 = 4b \Rightarrow b = 3 \), solving for \( c = 5 \), so the middle number is **5**.",
           "Let's go step by step to find the correct number at vertex \( X \).  1. The prism consists of **two triangular faces** and **three square faces**.2. Each **square face** has four numbers that sum to the same total.3. We are given **1 at one vertex** and **5 at another**.4. Let’s assign numbers **1, 2, 3, 4, 5, 6** to the vertices.5. By ensuring that the sum of the four numbers around each square is consistent, the correct number at \( X \) is found to be **2**.",
           "Observing the spiral pattern, numbers increase outward in a counterclockwise direction, forming concentric loops; since 625, 626, and 627 are consecutive, they follow this order in the spiral: 625 appears first, followed by 626, then 627.",
           "Analyze the multiplication table: (1) The top row and left column are multipliers. (2) Each cell is their product. (3) Known values: \(6 \times 7 = 42\), \(6 \times 3 = 18\), \(6 \times 6 = 36\), \(6 \times 4.5 = 27\). (4) **M** is in a row where the first column is missing, but 36 suggests multiplication by 6. (5) **T** follows the same pattern, confirming **M = T**.",
           "To solve, observe the 5-column structure where each row increases by 5. The missing piece must match this pattern. Checking options: (A) has a difference of 5, (B) does not, (C) follows the rule, (D) does not, (E) does not. Thus, the correct answer is **C (69, 72)**.",
           "Heinzi initially spent 130 KC (150 - 20 KC), then exchanged one toy and got 5 KC back, making his final spending 125 KC; the only toys matching this sum are the Carriage (73 KC) and the Aeroplane (52 KC), so he took them home.",
           "Each digit 0-6 is used once; their total sum is 21. Since two three-digit numbers sum to another three-digit number without carry-over, the missing digit in the grey box must be 5 to balance the equation.",
           "Bowl Z must be placed between Q and R because its pattern suggests it is slightly heavier than Q but lighter than R. By analyzing the shapes, Q has the lightest elements (three triangles and a square), while R has heavier round shapes. Z, containing a mix of triangles, circles, and squares, fits naturally between Q and R in terms of increasing weight.",
           "You're absolutely right! Let's summarize the reasoning concisely in one line:  Since the sum of each ring must be 55, solving for \( Y \) in \( Y + 11 + 14 + 2 + 13 + 7 = 55 \) gives \( Y = 8 \). Substituting \( Y = 8 \) in the upper ring equation \( 9 + 9 + Y + 11 + 8 + X = 55 \) results in \( 45 + X = 55 \), leading to \( X = 10 \).",
           "The total distance is \(3s\), and the total time is \(\frac{s}{5} + \frac{s}{15} + \frac{s}{20} = \frac{19s}{60}\), so the average velocity is \( v_{\text{avg}} = \frac{3s}{\frac{19s}{60}} = \frac{180}{19} \approx 9.47 \) cm/min."]

df_testmini['solution']=solution

print(df_testmini['decoded_image'])

df_testmini.to_csv("algebra_testmini.csv", sep=',', encoding='utf-8', index=False, header=True)

dataframe_question=pd.read_csv('algebra_testmini.csv')

print(dataframe_question['solution'])